"""updated fields and new roles

Revision ID: 11937f0e2ee6
Revises: 79dad2f37a84
Create Date: 2026-03-24 12:04:54.069306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11937f0e2ee6'
down_revision: Union[str, Sequence[str], None] = '79dad2f37a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


userrole_enum = sa.Enum('USER', 'ADMIN', name='userrole')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    userrole_enum.create(bind, checkfirst=True)

    op.add_column(
        'users',
        sa.Column(
            'role',
            userrole_enum,
            nullable=False,
            server_default='USER',
        ),
    )
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'role', server_default=None)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'role')
    userrole_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
